name: maxdircut
channels:
  - mosek
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - clarabel=0.6.0
  - cvxpy=1.4.1
  - cvxpy-base=1.4.1
  - ecos=2.0.11
  - intel-openmp=2023.2.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.5.0
  - libffi=3.4.2
  - libhwloc=2.9.3
  - libiconv=1.17
  - liblapack=3.9.0
  - libosqp=0.6.3
  - libqdldl=0.1.5
  - libsqlite=3.43.2
  - libxml2=2.11.5
  - libzlib=1.2.13
  - mkl=2023.2.0
  - mosek=10.1.15
  - numpy=1.26.0
  - openssl=3.1.3
  - osqp=0.6.3
  - pip=23.3.1
  - pthreads-win32=2.9.1
  - python=3.11.6
  - python_abi=3.11
  - qdldl-python=0.1.5.post2
  - scipy=1.11.3
  - scs=3.2.3
  - setuptools=68.2.2
  - tbb=2021.10.0
  - tk=8.6.13
  - tzdata=2023c
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.36.32532
  - vs2015_runtime=14.36.32532
  - wheel=0.41.2
  - xz=5.2.6
